// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/localuser.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 5926703204568474464),
      name: 'LocalUser',
      lastPropertyId: const IdUid(4, 488631004131730146),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 5432630656151933804),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 6049856766618222361),
            name: 'userId',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 5046010777159906517),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 488631004131730146),
            name: 'imgUrl',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 5926703204568474464),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    LocalUser: EntityDefinition<LocalUser>(
        model: _entities[0],
        toOneRelations: (LocalUser object) => [],
        toManyRelations: (LocalUser object) => {},
        getId: (LocalUser object) => object.id,
        setId: (LocalUser object, int id) {
          object.id = id;
        },
        objectToFB: (LocalUser object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final imgUrlOffset = fbb.writeString(object.imgUrl);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.userId);
          fbb.addOffset(2, nameOffset);
          fbb.addOffset(3, imgUrlOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = LocalUser(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              userId:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
              imgUrl: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, ''),
              name: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [LocalUser] entity fields to define ObjectBox queries.
class LocalUser_ {
  /// see [LocalUser.id]
  static final id = QueryIntegerProperty<LocalUser>(_entities[0].properties[0]);

  /// see [LocalUser.userId]
  static final userId =
      QueryIntegerProperty<LocalUser>(_entities[0].properties[1]);

  /// see [LocalUser.name]
  static final name =
      QueryStringProperty<LocalUser>(_entities[0].properties[2]);

  /// see [LocalUser.imgUrl]
  static final imgUrl =
      QueryStringProperty<LocalUser>(_entities[0].properties[3]);
}
